### ISSUE TITLE
Missing ft_100d_oa_cr.tar.gz file?

### ISSUE THREAD

**Issue by meaningfromdata** [gweissman/clinical_embeddings#1]
Hi @gweissman and @zachflam,
Thank you for making these word embeddings available.  Your 100-dimension fastText embedding trained on the Open Access-All set appears to be missing or possibly misnamed.  When I click on the link for it I see the "w2v_600d_oa_cr.tar.gz" file instead.

**Comment by gweissman** [comment]
You can download the fastText 100 dimensional embeddings trained on all open access manuscripts here: https://upenn.box.com/s/dsj1att1n0dvz6detp1bde1cxw1o6n84

I've updated the URL. Thanks for letting me know.
